from .registry import ExerciseRegistry
from .bicep_curl import BicepCurlTracker
from .squat import SquatTracker
from .pushup import PushUpTracker
from .lunges import LungesTracker
from .shoulder_press import ShoulderPressTracker
from .jumping_jacks import JumpingJacksTracker
from .high_knees import HighKneesTracker
from .mountain_climbers import MountainClimbersTracker
from .plank import PlankTracker
from .glute_bridge import GluteBridgeTracker
from .situps import SitUpsTracker
from .crunches import CrunchesTracker
from .leg_raise import LegRaisesTracker
from .russian_twist import RussianTwistTracker
from .bicycle_crunch import BicycleCrunchTracker
from .side_lunge import SideLungeTracker
from .calf_raise import CalfRaiseTracker
from .front_raise import FrontRaiseTracker
from .lateral_raise import LateralRaiseTracker
from .tricep_extension import TricepExtensionTracker
